server:
  servlet:
    context-path: /attendance-backend
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 25
    show-sql: true
  profiles:
    active: dev
