spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/profile-service
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
server:
  address: 192.168.62.80
  port: 8080